alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"
alias ll="ls -lh"
alias la="ll -a"
alias ls="ls --color=always --group-directories-first -a"
alias lsd="echo 'I wish!'"
alias cd..="cd .."
alias dc="cd"
alias netstat_osx="sudo lsof -i -P"
alias gut="gti"
alias fuck='sudo $(history -p !-1)'
alias startpostgres="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start"
alias whatip="curl -s ifconfig.me/ip"
alias rebasegit="git reset --hard && git checkout master && git rebase --abort"
alias upgrade="sudo apt-get update && sudo apt-get upgrade"
